<?php
/**
 * @file
 * Code for the CA Adv Staff feature.
 */

include_once 'ca_adv_staff.features.inc';

/**
 * Implements hook_menu().
 */
function ca_adv_staff_menu() {
  $items['admin/config/worx_features/adv-staff'] = array(
    'title' => 'Adv Staff Configuration',
    'description' => 'Override settings for ca_adv_staff',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_adv_staff_settings_form'),
    'access arguments' => array('worx features admin'),
    'file' => 'ca_adv_staff.admin.inc',
    'file path' => drupal_get_path('module', 'ca_adv_staff'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/worx_features/adv-staff/general'] = array(
    'title' => 'General Settings',
    'description' => 'Override settings for ca_adv_staff',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_adv_staff_settings_form'),
    'access arguments' => array('worx features admin'),
    'file' => 'ca_adv_staff.admin.inc',
    'file path' => drupal_get_path('module', 'ca_adv_staff'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function ca_adv_staff_menu_alter(&$items) {
  $items['staff']['title'] = variable_get('ca_adv_staff_menu_title', 'Staff');
}

/**
 * Implements hook_panels_pre_render().
 */
function ca_adv_staff_panels_pre_render($panel, $renderer) {
  foreach ($panel->content as $key => $value) {
    if ($value->subtype == 'ca_adv_staff_category_list-ca_adv_staff_cat_list_1') {
      $panel->title = variable_get('ca_adv_staff_panel_title', 'Staff');
    } elseif ($value->subtype == 'ca_adv_staff_category_list-ca_adv_staff_cat_list_2') {
      $panel->title = variable_get('ca_adv_staff_panel_title', 'Staff');
    } elseif ($value->subtype == 'ca_adv_staff_category_list-ca_adv_staff_cat_list_3') {
      $panel->title = variable_get('ca_adv_staff_panel_title', 'Staff');
    } elseif ($value->subtype == 'ca_adv_staff_staff_list-staff_grouped_member_list_1') {
      $panel->title = variable_get('ca_adv_staff_panel_title', 'Staff');
    }
  }
}

/**
 * Implements hook_views_pre_render().
 */
function ca_adv_staff_views_pre_view(&$view, &$display_id, &$args) {
  if ($display_id == 'ca_adv_staff_cat_list_1') {
    $view->set_items_per_page(variable_get('ca_adv_staff_cat_list_count', 12));
  } elseif ($display_id == 'ca_adv_staff_cat_list_2') {
    $view->set_items_per_page(variable_get('ca_adv_staff_cat_list_count', 12));
  } elseif ($display_id == 'ca_adv_staff_cat_list_3') {
    $view->set_items_per_page(variable_get('ca_adv_staff_cat_list_count', 12));
  }
  if ($display_id == 'staff_member_list_1') {
    $view->set_items_per_page(variable_get('ca_adv_staff_staff_grid_count', 12));
  } elseif ($display_id == 'staff_member_list_2') {
    $view->set_items_per_page(variable_get('ca_adv_staff_staff_grid_count', 12));
  } elseif ($display_id == 'staff_member_list_3') {
    $view->set_items_per_page(variable_get('ca_adv_staff_staff_list_count', 5));
  } elseif ($display_id == 'staff_member_list_4') {
    $view->set_items_per_page(variable_get('ca_adv_staff_staff_list_count', 5));
  } elseif ($display_id == 'staff_grouped_member_list_1') {
    $view->set_items_per_page(variable_get('ca_adv_staff_staff_grid_count', 12));
  }
}

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function ca_adv_staff_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;
  }
}

